name: Update and Compact AWS IP Ranges

on:
  # Schedule the workflow to run once a day at 10:00 AM UTC.
  schedule:
    - cron: '0 10 * * *'
  # Allow the workflow to be triggered manually from the Actions tab.
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the repository content

    steps:
      - name: Check out repository
        # This action checks out your repository under $GITHUB_WORKSPACE.
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Set up Python
        # This action sets up the Python environment.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        # Install the 'requests' library from requirements.txt.
        run: pip install -r requirements.txt

      - name: Run script to fetch and compact ranges
        id: run-script
        # Execute the Python script.
        run: |
          python compact_ranges.py

      - name: Commit and push if content has changed
        # This action handles committing and pushing changes.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The file to commit.
          commit_message: "Update and compact AWS IP ranges"
          # Only commit json file changes.
          file_pattern: ip-ranges-*.json
          # Rebase before pushing changes.
          push_options: "--force"

